# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - pytest:
          requires:
            - build
      - deploy-doc:
          requires:
            - build
jobs:
  build:
    docker:
      - image: circleci/python:3.6.10-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - venv-{{ checksum "requirements-dev.txt" }}-{{ checksum "setup.py" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            # pip need to be upgraded for TF 1.15
            pip install --upgrade pip
            # Install the requirements but remove PiNN            
            pip install .[cpu]
            pip uninstall -y pinn
            # Install requirements for testing
            pip install -r requirements-dev.txt
      - save_cache:
          paths:
            - ./venv
          key: venv-{{ checksum "requirements-dev.txt" }}-{{ checksum "setup.py" }}-{{ checksum ".circleci/config.yml" }}
  pytest:
    docker:
      - image: circleci/python:3.6.10-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - venv-{{ checksum "requirements-dev.txt" }}-{{ checksum "setup.py" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pip install -e .
            export CUDA_VISIBLE_DEVICES=''
            pytest --forked tests/ --cov=pinn
            codecov --token=$CODECOV_TOKEN
  deploy-doc:
    docker:
      - image: circleci/python:3.6.10-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - venv-{{ checksum "requirements-dev.txt" }}-{{ checksum "setup.py" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Deploy doc
          command: |
            sudo apt-get update
            sudo apt-get install pandoc            
            . venv/bin/activate
            pip install -e .
            ./.circleci/build_doc.sh
